os: linux
dist: bionic
language: php

addons:
  artifacts:
    paths:
      - ./tmp/e2e-screenshots

services:
  - xvfb
  - mysql
  - docker

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

env:
  - WP_VERSION=latest
  - WP_VERSION="5.6"
  - WP_VERSION="5.5"
  - WP_VERSION="5.4"
  - WP_VERSION=nightly

php:
  - "8.0"
  - "7.4"
  - "7.3"
  - "7.2"

jobs:
  fast_finish: true
  allow_failures:
  - env: WP_VERSION=nightly
  include:
  - name: "eslint"
    language: node_js
    node_js: lts/*
    install:
      - npm ci
    script:
      - npm run lint:js
    after_script:
  - name: "phpcs"
    php: 8.0
    install:
      - composer install
    script:
      - composer run check-cs-errors
    after_script:

before_install:
  # Disable xDebug for faster builds
  - |
    if [ "1" != $RUN_CODE_COVERAGE ] && [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    fi
  # Raise PHP memory limit to 2048MB
  - echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  # Install composer deps.
  - composer install
  # Upgrade docker-compose.
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.25.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  # Setup and Install Node.
  - nvm install --lts
  - node -v
  - npm -v
  - npm ci
  # Build static assets.
  - npm run build:scripts
  # Start the Environment.
  - composer run env up
  # Setup Environment.
  - composer run env:setup
  # Upgrade/Downgrade WP Core where appropriate.
  - |
    if [ "latest" != $WP_VERSION ]; then
      ./vendor/bin/llms-env wp core update --version=$WP_VERSION --force
      ./vendor/bin/llms-env wp core update-db
    fi;
  - ./vendor/bin/llms-env wp core version

script:
  - npm run test

after_script:
  - ./vendor/bin/llms-env down

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: VzwXDPjuNCrKed9ACY7dwzyIjcnt6G1iC1LnKAOIx9fyPZ7TARLIf5bSa9M7P5w4uQHK7kpm5yFNtPHKGwaazZnCZxH8jcDMc4M8y3w6j9uNlbidOgfrCpp07lY6kpd8ViR7ANZ4V5Noz+ts8/gSA0yUib6vGP87s6RKHTyVTfNuFmHui7t6vF3S1VCXm4JmOrqmZbY9DlN+8JcyE0Ao3KOk/UDSCZICqo7cYnMci2oHGfb+2VRu49B61tASnV0r/dRu7gjEQTtqwElIJfuP0hGeAYc6bee5vFLA4EIdz2TMgr/Fm1El5eIg+1ZB4bOVEHzUlonLLGaUlqcYfKtmmYiV8BBnte1xBlEflLxYj92ethTUtTvkicVmtK50IlyL8kpb4WBwhXMEjSoKGLmdfaeNGKZ0vS/BnyDA0eWmt4EQ5ZVQL50ukhvmOAXhMB5T+K6Bg6T3yJzXIxej0MrSSNVygpeIwl5RqleXOKJJtJe3TsrsQfdqidXVrKAGSrwlwDRSMLC7JN3l99+5PEXzgb106TE0TBgrMOEClTVyH4gAjplqQ70diw9SAp0rnU518dTDj9HMvZ7KcGQgnAzKI82iB1LaWsWrMjqHtPbn/h+2vRDQNRnx8umnCmC8ezRr4l+xZ8Cb9KgrhvJW+bed3pQFmD/LerSuW6ZgHFsN/KI=

