import:
  - gocodebox/lifterlms:.config/travis/main.yml
  - gocodebox/lifterlms:.config/travis/e2e.yml

jobs:
  exclude:
  - env: WP_VERSION="5.3"
  - env: WP_VERSION="5.2"

  include:
  - name: "eslint"
    language: node_js
    node_js: lts/*
    install:
      - npm ci
    script:
      - npm run lint:js
    after_script:
